AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.10

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
